before_install:
    - eval "${MATRIX_EVAL}"
language: c
compiler:
    - clang
    - gcc -std=c99
before_script:
    - sudo apt-get install freeglut3-dev libglew-dev libdevil-dev libxml2
script:
    - mkdir build
    - cd build
    - cmake ../src
    - cd Generator
    - make
    - cd ../Engine
    - make
after_script:
    - bash -c "$(curl -fsSL https://raw.githubusercontent.com/MaT1g3R/travis_discord/master/travis.sh)"
notifications:
  email: false
