language: c
compiler:
    - clang
    - gcc
before_script:
    - sudo apt-get install freeglut3-dev
    - mkdir build
    - cmake src/ -DCMAKE_SOURCE_DIR="src" -DCMAKE_BINARY_DIR="build"
script:
    - cd build/Generator
    - make
    - cd ../Engine
    - make
