language: c
compiler:
    - clang
    - gcc
before_script:
    - sudo apt-get install freeglut3-dev
    - mkdir build
    - cmake src/
script:
    - cd build/Generator
    - make
    - cd ../Engine
    - make
