language: c
compiler:
    - clang
    - gcc
before_script:
    - sudo apt-get install freeglut3-dev
script:
    - mkdir build
    - cd build
    - cmake ../src
    - cd Generator
    - make
    - cd ../Engine
    - make
