language: c
compiler:
    - clang
    - gcc
before_script:
    - apt-get install freeglut3-dev
    - mkdir build
    - cd build
    - cmake ../src
script:
    - cd build/Generator
    - make
    - cd build/Engine
    - make
-sudo: false
