matrix:
    include:
        - os: linux
          addons:
              apt:
                  source:
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-4.9
        env:
            - MATRIX_EVAL="CC=gcc-4.9"
before_install:
    - eval "${MATRIX_EVAL}"
language: c
compiler:
    - clang
    - gcc
before_script:
    - sudo apt-get install freeglut3-dev
    - sudo apt-get install libglew-dev
script:
    - mkdir build
    - cd build
    - cmake ../src
    - cd Generator
    - make
    - cd ../Engine
    - make
after_script:
    - bash -c "$(curl -fsSL https://raw.githubusercontent.com/MaT1g3R/travis_discord/master/travis.sh)"
